# Generated by Django 4.1.1 on 2022-09-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbSubject',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=1000)),
                ('is_hot', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_subject',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('tel', models.CharField(max_length=20, verbose_name='手机号')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('last_visit', models.DateTimeField(null=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='TbTeacher',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=True)),
                ('birth', models.DateField()),
                ('intro', models.CharField(max_length=1000)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('gcount', models.IntegerField()),
                ('bcount', models.IntegerField()),
                ('sno', models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.tbsubject')),
            ],
            options={
                'db_table': 'tb_teacher',
            },
        ),
    ]
