# Generated by Django 4.1.1 on 2022-09-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_test', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbToken',
        ),
    ]
